---
 - hosts: web-servers
   tasks:
      -  name: Remove and purge apache2
         apt:
            name: apache2
            state: absent
            purge: true

      -  name: delete /var/www/ directory
         file:
            state: absent
            path: "/var/www/"

      -  name: install "apache2" package
         apt:
            name: apache2
            state: present

